var qunit = require('qunit');
window.q = qunit;
window.test = qunit.test;
window.equal = qunit.equal;
window.ok = qunit.ok;
window.expect = qunit.expect;
require('raphael');

require("./vexflow_test_helpers.js");
require("./mocks.js");
require("./stave_tests.js");
require("./tabstave_tests.js");
require("./voice_tests.js");
require("./stavenote_tests.js");
require("./tabnote_tests.js");
require("./tickcontext_tests.js");
require("./modifier_tests.js");
require("./accidental_tests.js");
require("./dot_tests.js");
require("./bend_tests.js");
require("./formatter_tests.js");
require("./stavetie_tests.js");
require("./tabtie_tests.js");
require("./tabslide_tests.js");
require("./beam_tests.js");
require("./auto_beam_formatting_tests.js");
require("./vibrato_tests.js");
require("./annotation_tests.js");
require("./tuning_tests.js");
require("./keysignature_tests.js");
require("./timesignature_tests.js");
require("./clef_tests.js");
require("./music_tests.js");
require("./keymanager_tests.js");
require("./articulation_tests.js");
require("./staveconnector_tests.js");
require("./percussion_tests.js");
require("./key_clef_tests.js");
require("./stavehairpin_tests.js");
require("./rhythm_tests.js");
require("./tuplet_tests.js");
require("./boundingbox_tests.js");
require("./textnote_tests.js");
require("./strokes_tests.js");
require("./stringnumber_tests.js");
require("./rests_tests.js");
require("./threevoice_tests.js");
require("./table_tests.js");
require("./gracenote_tests.js");
require("./curve_tests.js");
require("./notehead_tests.js");
require("./staveline_tests.js");
require("./ornament_tests.js");
require("./pedalmarking_tests.js");
require("./textbracket_tests.js");